### ISSUE TITLE
issue on main website : stats contirubtion

### ISSUE THREAD

**Issue by Grummfy** [hoaproject/Central#68]
In the Activity part in the right bottom, no more graph where displayed

**Comment by Pierozi** [comment]
This is due to CSP `unsafe-inline`, I will check if I can fix it on server configuration.

```log
EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "default-src 'self' *.hoa-project.net *.hoa.io *.github.io *.github.com *.discourse.org *.tile.openstreetmap.org 'unsafe-inline'". at new Function (<anonymous>) at https://static.hoa-project.net/Javascript/D3.js:1998:17 at Function.dsv.parseRows (https://static.hoa-project.net/Javascript/D3.js:2046:23) at Function.dsv.parse (https://static.hoa-project.net/Javascript/D3.js:1996:18) at Object.response (https://static.hoa-project.net/Javascript/D3.js:1987:18) at XMLHttpRequest.respond (https://static.hoa-project.net/Javascript/D3.js:1902:29)
```

**Comment by Pierozi** [comment]
It's fixed, thanks for the reporting!

**Comment by Hywan** [comment]
Thanks!
